# name: Deploy New Version

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: Use Node.js 14
#       uses: actions/setup-node@v1
#       with:
#         node-version: '14.x'
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#     - name: npm install, build, test, publish
#       run: |
#         node --version
#         npm --version
#         npm ci
#         npm run build --if-present
#         npm test
#       env:
#         CI: true
#     - name: rollingversions check
#       run: |
#         echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
#         npx rollingversions publish -d -g ${{ secrets.GITHUB_TOKEN }}
#         npx rollingversions publish -g ${{ secrets.GITHUB_TOKEN }}
